Zavrsni.Web/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.Routing;
using Microsoft.EntityFrameworkCore;
using Zavrsni.DAL;
using Zavrsni.Model;
using Zavrsni.Web.Areas.Identity.Pages.Account;
using Zavrsni.Web.Models;
using Zavrsni.Web.Util;

namespace Zavrsni.Web.Controllers
{
    [Authorize(Policy = "RequireAdministrator")]
    public class AdminController : Controller
    {
        private readonly DataManagerDbContext _dbContext;
        private readonly UserManager<AppUser> _userManager;
        private readonly IUserStore<AppUser> _userStore;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly ILogger<RegisterModel> _logger;
        private readonly IEmailSender _emailSender;
        private readonly IUrlHelperFactory _urlHelperFactory;
        private readonly DailyCoService _dailyCoService;
        public AdminController(DataManagerDbContext dbContext,
           UserManager<AppUser> userManager,
           IUserStore<AppUser> userStore,
           SignInManager<AppUser> signInManager,
           ILogger<RegisterModel> logger,
           IEmailSender emailSender,
           IUrlHelperFactory urlHelperFactory,
           DailyCoService dailyCoService)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _userStore = userStore;
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
            _urlHelperFactory = urlHelperFactory;
            _dailyCoService = dailyCoService;
        }

        [Route("kreirajDoktora")]
        public IActionResult KreirajDoktora()
        {
            this.FillDropdownSpecijalizacije();
            return View();
        }
        [HttpPost]
        [Route("kreirajDoktora")]
        public async Task<IActionResult> KreirajDoktoraAsync(DoktorKreiranje model)
        {
            Doktor doktor = new Doktor
            {
                Ime = model.Ime,
                Prezime = model.Prezime,
                SpecijalizacijaID = model.SpecijalizacijaID,
                Email = model.Email,
                Telefon = model.Telefon,
                Adresa = model.Adresa,
                Grad = model.Grad,
                Drzava = model.Drzava,
                JMBG = model.JMBG,
                KorisnickoIme = model.KorisnickoIme,
                Titula = model.Titula,
                PocetakRadnogVremena = model.PocetakRadnogVremena,
                KrajRadnogVremena = model.KrajRadnogVremena
            };

            var pacijentList = new List<Pacijent>();
            doktor.Pacijenti = pacijentList;
            ModelState.Remove("Specijalizacija");
            doktor.Specijalizacija = _dbContext.Specijalizacije.Find(model.SpecijalizacijaID);
            var returnUrl = Url.Content("~/");

            if (ModelState.IsValid)
            {
                var urlHelper = _urlHelperFactory.GetUrlHelper(ControllerContext);
                var rc = new DoktorRegister(_userManager, _userStore, _signInManager, _logger, _emailSender, _dbContext, urlHelper);
                var success = await rc.KreirajNovogDoktora(doktor, model, returnUrl, Request.Scheme);

                TempData["AlertMessage"] = "Doktor uspjesno kreiran";
                this.FillDropdownSpecijalizacije();

                //_dbContext.Doktori.Add(model);
                //_dbContext.SaveChanges();
                return Redirect("/administracijaDoktora");
            }
            else
            {
                this.FillDropdownSpecijalizacije();
                return View();
            }
        }
        [Route("/administriranjeDoktora")]
        public IActionResult AdministriranjeDoktora()
        {

           var doktori = _dbContext.Doktori.Include(p => p.Specijalizacija).ToList();
            return View(doktori);
        }
        public IActionResult AboutDoktor(int id)
        {
            var doktor = _dbContext.Doktori.Include(p => p.Specijalizacija).Include(p => p.Pacijenti).FirstOrDefault(p => p.DoktorID == id);
            return View(doktor);
        }
        public IActionResult ObrisiDoktora(int id)
        {
            var user = _dbContext.Users.FirstOrDefault(p => p.DoktorID == id);
            var doktor = _dbContext.Doktori.Include(p => p.Pacijenti).FirstOrDefault(p => p.DoktorID == id);
            _dbContext.Users.Remove(user);
            _dbContext.Doktori.Remove(doktor);
            _dbContext.SaveChanges();
            return Redirect("/administriranjeDoktora");
        }
        [Route("/administriranjePacijenta")]
        public IActionResult AdministriranjePacijenta()
        {
            var pacijenti = _dbContext.Pacijenti.Include(p => p.Doktori).ToList();
            return View(pacijenti);
        }
        public IActionResult AboutPacijent(int id)
        {
            var pacijent = _dbContext.Pacijenti.Include(p => p.Doktori).FirstOrDefault(p => p.PacijentID == id);
            return View(pacijent);
        }
        public IActionResult ObrisiPacijenta(int id)
        {
            var user = _dbContext.Users.FirstOrDefault(p => p.PacijentID == id);
            var pacijent = _dbContext.Pacijenti.Include(p => p.Doktori).FirstOrDefault(p => p.PacijentID == id);
            _dbContext.Users.Remove(user);
            _dbContext.Pacijenti.Remove(pacijent);
            _dbContext.SaveChanges();
            return Redirect("/administriranjePacijenta");
        }




        private void FillDropdownSpecijalizacije()
        {
            var selectItems = new List<SelectListItem>();

            //Polje je opcionalno
            var listItem = new SelectListItem();
            listItem.Text = "- odaberite spec. -";
            listItem.Value = "";
            selectItems.Add(listItem);

            foreach (var category in _dbContext.Specijalizacije)
            {
                listItem = new SelectListItem(category.Naziv, category.SpecijalizacijaID.ToString());
                selectItems.Add(listItem);
            }

            ViewBag.Specijalizacije = selectItems;
        }
    }
}

Zavrsni.Web/Controllers/DoktorController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.Routing;
using Microsoft.EntityFrameworkCore;
using System.Text;
using Zavrsni.DAL;
using Zavrsni.Model;
using Zavrsni.Web.Areas.Identity.Pages.Account;
using Zavrsni.Web.Models;
using Zavrsni.Web.Util;
using System.Security.Cryptography;
using Sqids;
using Microsoft.AspNetCore.Authorization;

namespace Zavrsni.Web.Controllers
{
    [Authorize(Policy = "RequireUserTypeDoktor")]
    public class DoktorController : Controller
    {
        private readonly DataManagerDbContext _dbContext;
        private readonly UserManager<AppUser> _userManager;
        private readonly IUserStore<AppUser> _userStore;
        private readonly SignInManager<AppUser> _signInManager;
        private readonly ILogger<RegisterModel> _logger;
        private readonly IEmailSender _emailSender;
        private readonly IUrlHelperFactory _urlHelperFactory;
        private readonly DailyCoService _dailyCoService;

        public DoktorController(DataManagerDbContext dbContext,
            UserManager<AppUser> userManager,
            IUserStore<AppUser> userStore,
            SignInManager<AppUser> signInManager,
            ILogger<RegisterModel> logger,
            IEmailSender emailSender,
            IUrlHelperFactory urlHelperFactory,
            DailyCoService dailyCoService)
        {
            _dbContext = dbContext;
            _userManager = userManager;
            _userStore = userStore;
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
            _urlHelperFactory = urlHelperFactory;
            _dailyCoService = dailyCoService;
        }

        [Route("pregledi")]
        [ActionName("NadolazeciPregledi")]
        public async Task<IActionResult> NadolazeciPreglediAsync()
        {
            var doktor = await _userManager.GetUserAsync(User);
            var pregledi = _dbContext.Pregledi.Include(p => p.Pacijent).Include(p => p.Doktor).Where(p => p.DoktorID == doktor.DoktorID).ToList();
            return View(pregledi);
        }
        [Route("pregledByID/{id}")]
        public IActionResult DetaljiOPregleduDoktor(int id)
        {
            var pregled = _dbContext.Pregledi.Include(p => p.Pacijent).Include(p => p.Doktor).FirstOrDefault(p => p.PregledID == id);

            return View(pregled);
        }
        [HttpPost]
        [Route("potvrdaPregleda")]
        public async Task<IActionResult> PotvrdiPregled(Pregled model)
        {
            Pregled pregled = _dbContext.Pregledi.Include(p => p.Pacijent).Include(p => p.Doktor).FirstOrDefault(p => p.PregledID == model.PregledID);
            pregled.Potvrdeno = true;
            var sqids = new SqidsEncoder<int>(new()
            {
                MinLength = 5,
            });
            var roomName = sqids.Encode(pregled.PregledID);
            var dailycoUrl = await _dailyCoService.CreateRoomAsync(roomName, pregled.DatumIVrijemePregleda);
            pregled.UrlVideopoziva = roomName;

            string body = string.Empty;
            using (StreamReader reader = new StreamReader("MailTemplate/EmailZaPacijentaPotvrda.html"))
            {
                body = reader.ReadToEnd();
            }
            body = body.Replace("{UserName}", pregled.Pacijent.ImePrezime);
            body = body.Replace("{DoktorName}", pregled.Doktor.ImePrezime);
            body = body.Replace("{DatumPregleda}", pregled.DatumIVrijemePregleda.ToString("d.M.yyyy"));
            body = body.Replace("{VrijemePregleda}", pregled.DatumIVrijemePregleda.ToString("HH:mm"));
            EmailConfirmation emailConfirmation = new EmailConfirmation();
            await emailConfirmation.SendEmail(pregled.Pacijent.Email, "Obavijest o potvrđenom pregledu", body);


            _dbContext.Pregledi.Update(pregled);
            _dbContext.SaveChanges();
            return Redirect("/pregledByID/" + model.PregledID);
        }

        [Route("videopoziv/{id}")]
        public IActionResult Videopoziv(string id)
        {
            var redir = "https://doc-online.daily.co/" + id;
            ViewBag.Url = "https://doc-online.daily.co/" + id;
            //redirect to link in new tab

            return View("VideopozivView", id);
        }
        [HttpPost]
        public IActionResult DodajBiljesku(Pregled model)
        {
            Pregled pregled = _dbContext.Pregledi.Include(p => p.Pacijent).Include(p => p.Doktor).FirstOrDefault(p => p.PregledID == model.PregledID);
            pregled.BiljeskeDoktora = model.BiljeskeDoktora;
            _dbContext.Pregledi.Update(pregled);
            _dbContext.SaveChanges();
            return Redirect("/pregledByID/" + model.PregledID);
        }

        [HttpPost]
        public IActionResult UrediBiljesku(Pregled model)
        {
            Pregled pregled = _dbContext.Pregledi.Include(p => p.Pacijent).Include(p => p.Doktor).FirstOrDefault(p => p.PregledID == model.PregledID);
            pregled.BiljeskeDoktora = model.BiljeskeDoktora;
            _dbContext.Pregledi.Update(pregled);
            _dbContext.SaveChanges();
            return Redirect("/pregledByID/" + model.PregledID);
        }
        [HttpPost]
        public async Task<IActionResult> PosaljiEmailAsync(DoktorEmailModel model)
        {
            var pacijent = _dbContext.Pacijenti.FirstOrDefault(p => p.PacijentID == model.PacijentID);
            var doktor = _dbContext.Doktori.FirstOrDefault(p => p.DoktorID == model.DoktorID);
            var pregled = _dbContext.Pregledi.Include(p => p.Pacijent).Include(p => p.Doktor).FirstOrDefault(p => p.PregledID == model.PregledID);

            string body = string.Empty;
            using (StreamReader reader = new StreamReader("MailTemplate/EmailMessageTemplate.html"))
            {
                body = reader.ReadToEnd();
            }
            body = body.Replace("{PregledDatum}", pregled.DatumIVrijemePregleda.ToString());
            body = body.Replace("{UserName}", pacijent.ImePrezime);
            body = body.Replace("{Poruka}", model.EmailPoruka);
            EmailConfirmation emailConfirmation = new EmailConfirmation();
            await emailConfirmation.SendEmail(pacijent.Email, "Nova poruka od doktora", body);
            return Redirect("/pregledByID/" + model.PregledID);
        }

        [Route("popisPacijenata")]
        public IActionResult PopisPacijenata()
        {
            var user = _userManager.GetUserAsync(User).Result;
            var doktor = _dbContext.Doktori.Include(p => p.Pacijenti).FirstOrDefault(p => p.DoktorID == user.DoktorID);
            return View(doktor.Pacijenti.ToList());
        }

        [Route("pacijent/{id}")]
        public IActionResult AboutPacijent(int id)
        {
            ViewBag.PacijentPregledi = _dbContext.Pregledi.Include(p => p.Doktor).Include(p => p.Pacijent).Where(p => p.PacijentID == id).ToList();
            var pacijent = _dbContext.Pacijenti.FirstOrDefault(p => p.PacijentID == id);
            return View(pacijent);
        }
        [ActionName("OtkaziPregled")]
        public async Task<IActionResult> OtkaziPregledAsync(OtkaziPregledModel model)
        {
            var pregled = _dbContext.Pregledi.Include(p => p.Pacijent).Include(p => p.Doktor).FirstOrDefault(p => p.PregledID == model.PregledID);

            string body = string.Empty;
            using (StreamReader reader = new StreamReader("MailTemplate/EmailZaPacijentaOtkazivanje.html"))
            {
                body = reader.ReadToEnd();
            }
            body = body.Replace("{UserName}", pregled.Pacijent.ImePrezime);
            body = body.Replace("{DoktorName}", pregled.Doktor.ImePrezime);
            body = body.Replace("{DatumPregleda}", pregled.DatumIVrijemePregleda.ToString("d.M.yyyy"));
            body = body.Replace("{VrijemePregleda}", pregled.DatumIVrijemePregleda.ToString("HH:mm"));
            EmailConfirmation emailConfirmation = new EmailConfirmation();
            await emailConfirmation.SendEmail(pregled.Pacijent.Email, "Obavijest o otkazivanju pregleda", body);


            _dbContext.Pregledi.Remove(pregled);
            _dbContext.SaveChanges();
            return Redirect("/pregledi");
        }





        private void FillDropdownSpecijalizacije()
        {
            var selectItems = new List<SelectListItem>();

            //Polje je opcionalno
            var listItem = new SelectListItem();
            listItem.Text = "- odaberite spec. -";
            listItem.Value = "";
            selectItems.Add(listItem);

            foreach (var category in _dbContext.Specijalizacije)
            {
                listItem = new SelectListItem(category.Naziv, category.SpecijalizacijaID.ToString());
                selectItems.Add(listItem);
            }

            ViewBag.Specijalizacije = selectItems;
        }
        public static byte[] GetHash(string inputString)
        {
            using (HashAlgorithm algorithm = SHA256.Create())
                return algorithm.ComputeHash(Encoding.UTF8.GetBytes(inputString));
        }

        public static string GetHashString(string inputString)
        {
            StringBuilder sb = new StringBuilder();
            foreach (byte b in GetHash(inputString))
                sb.Append(b.ToString("X2"));

            return sb.ToString();
        }
    }
}

Zavrsni.Web/Views/Shared/_Layout.cshtml
@using Zavrsni.Model;
@using Microsoft.AspNetCore.Identity;
@inject UserManager<AppUser> userManager;
<!DOCTYPE html>
<html lang="en">
<head>
    @{
        var daily = "@daily";
    }
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @await RenderSectionAsync("css", required: false)

    <title>@ViewData["Title"] - Doc Online</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Zavrsni.Web.styles.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.7.1.js"
            integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4="
            crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.39.0/css/tempusdominus-bootstrap-4.min.css" integrity="sha384-Vkz7yPDaRmUpDBH1UoJjXpzP0Ny0gN7RGhbmEY6ibJb6gp22s3FsNyT8p1zXftx8" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Doc Online</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @{
                        var user = await userManager.GetUserAsync(User);
                        if(user == null)
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" href="/o-nama">O nama</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Pravila privatnosti</a>
                                </li>
                            </ul>
                        }
                        else if (user.UserType == UserType.Doktor)
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" href="/o-nama">O nama</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Pravila privatnosti</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Doktor" asp-action="NadolazeciPregledi">Pregledi</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Doktor" asp-action="PopisPacijenata">Moji pacijenti</a>
                                </li>
                            </ul>
                        }
                        else if (user.UserType == UserType.Pacijent)
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" href="/o-nama">O nama</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Pravila privatnosti</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="OdabirDoktora">Odaberi doktora</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="KreirajPregled">Zatraži pregled</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MojiPregledi">Moji pregledi</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="MojiDoktori">Moji doktori</a>
                                </li>
                            </ul>
                        }
                        else if (user.UserType == UserType.Administrator)
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" href="/o-nama">O nama</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Pravila privatnosti</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="KreirajDoktora">Kreiranje novog doktora</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AdministriranjeDoktora">Administriranje doktora</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="AdministriranjePacijenta">Administriranje pacijenta</a>
                                </li>
                            </ul>
                        }
                    }

                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Doc Online - <a asp-area="" asp-controller="Home" asp-action="Privacy">Pravila privatnosti</a>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.39.0/js/tempusdominus-bootstrap-4.min.js" integrity="sha384-Cm3mBuROFbGzTOwKNQNXRgnLyIh92fC4ldgkUvJHiw/Z39E6YBDo8aK6aNFFVcfv" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>